#    * @project_name : Gifted-Md
#    * @author : @GiftedTech
#    * @youtube : https://www.youtube.com/c/@giftedtechnexus
#    * @description : Suhail-Md ,A Multi-functional whatsapp bot md.
#    * @version 2.o.o
# 
# Don't change this [ /SuhailTechInfo/ ] name!
# Change from below link, else bot not works!



FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/Giftedmaurice/gifted-mdV2 /root/Gifted
WORKDIR /root/Gifted/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
